### ISSUE TITLE
Requiring npm modules...

### ISSUE THREAD

**Issue by JoeDRL** [alongubkin/spider#129]
Hey,

I've been trying for the whole day to require an npm package in my spider script and can't make it work.
```
    use :node;
    var axios = require("axios");
```

This gives: Error: Cannot find module 'axios'.

```
   import * as axios from 'axios';
```

This too..

Of course the axios package is installed in my local node_modules folder.
What am I doing wrong here?

**Comment by pyros2097** [comment]
Its already been filed you can check it out here...
https://github.com/alongubkin/spider/issues/108
