### ISSUE TITLE
Is Development still Happening or is this project Dead?

### ISSUE THREAD

**Issue by pyros2097** [alongubkin/spider#131]

**Comment by alongubkin** [comment]
It's not dead. I'm currently taking a break and I'll continue development later this year. There are many things to do: bugfixes, Babel instead of Traceur, ES6 classes, and more.

**Comment by pyros2097** [comment]
Nice!! Can't wait for the react integration. Spider is the only thing that's going to keep me on nodejs or iojs platform. I was planning to switch to Go because of all the headaches we had with coffeescript. Plus I like the go syntax maybe a gofmt like formatter might also do good to make code standardised.

**Comment by bucaran** [comment]
> I was planning to switch to Go because of all the headaches we had with coffeescript.

@pyros2097 Of course, this probably makes sense to you, but I have no idea what you are talking about here. What is CoffeeScript has to do with this? :smile:

**Comment by pyros2097** [comment]
So we do all my backend code in coffeescript and sometimes get a lot of weird errors even in production  untraceable and its mostly related to some variable being undefined or overwritten or some the way coffeescript transpiles to, without us knowing it. So after I found out spiderscript had features like Go and also threw a lot of compiler errors if something was wrong with your code (which btw coffeescript doesn't do) I was impressed and planned on rewriting some of my projects to spiderscript.

**Comment by bucaran** [comment]
Fair enough. You can also use plain JavaScript.

**Comment by pyros2097** [comment]
Nooooooo.........oooo!!!!!! Its been 3 months already !!

**Comment by yosbelms** [comment]
Hi @pyros2097 "Go" like syntax has inspired more than one javascript transpiler project, you may want to check yosbelms/cor if still feel Go-syntax passion.

**Comment by pyros2097** [comment]
@yosbelms Cor seems interesting ... especially the way classes are initialized .. gives way to declarative interfaces.. thanks.
