### ISSUE TITLE
CLI execution is still broken

### ISSUE THREAD

**Issue by zekesonxx** [alongubkin/spider#94]
Do not close this issue until it's actually fixed. This is a core feature and is almost certainly turning people off to spider. 

Things that have not fixed it: ad09f6b, 92228e3, 646c6fb, 1f6edd1, 8d269ea.

**Comment by sloosch** [comment]
Maybe i'm missing something but doing "spider -c path/to/a.spider" doesn't work. I need to change the cwd first to the source folder and then call "spider -c a.spider" otherwise following error is thrown:
````
/usr/local/lib/node_modules/spider-script/lib/spider.js:79
      var lines = content.split("\n");
                         ^
TypeError: Cannot read property 'split' of undefined
    at Object.exports.formatErrors (/usr/local/lib/node_modules/spider-script/lib/spider.js:79:26)
    at /usr/local/lib/node_modules/spider-script/cli.js:67:26
    at fs.js:224:20
    at Object.oncomplete (fs.js:93:15)
````
tried with version 0.1.5
